# Creative investor configuration
env_path: 'C:\Users\byeun\workspace\perfectdays\.env'
output_dir: 'C:\Users\byeun\Downloads\strategy01_creative'
max_workers: 6
tickers: null

budget: 120000000
z_vol: 1.2
vwap_rel_std_max: 0.007
enhanced_sell: true
sell_after_days: 5
min_hold_days: 1
prioritize_time_exit: false

take_profit_pct: 0.06
stop_loss_pct: 0.03
trailing_stop_pct: 0.025
partial_sell_ratio: 0.4
