# Aggressive investor configuration
env_path: 'C:\Users\byeun\workspace\perfectdays\.env'
output_dir: 'C:\Users\byeun\Downloads\strategy01_aggressive'
max_workers: 8
tickers: null

budget: 200000000
z_vol: 0.75
vwap_rel_std_max: 0.01
enhanced_sell: false
sell_after_days: 3
min_hold_days: 0
prioritize_time_exit: false

take_profit_pct: null
stop_loss_pct: null
trailing_stop_pct: null
partial_sell_ratio: null
