# 실행 환경 및 출력 설정
env_path: 'C:\Users\by003457\workspace\perfectdays\.env'
output_dir: 'C:\Users\by003457\Downloads\strategy01'
max_workers: 6
# tickers:
# 	- A010420
# 	- A005930

# 투자 에이전트(InvestorAgent) 주요 파라미터 설정 예시
budget: 10000000  # 초기 자본
z_vol: 1.5
vwap_rel_std_max: 0.03
enhanced_sell: true    # 고급 매도 로직 사용 여부
sell_after_days: 5     # 보유 후 매도까지의 최소 일수
# 전략 규칙이 존재하는 동안 최소 보유 일수 (0이면 제한 없음)
min_hold_days: 0
# 시간 기반 청산을 우선시할지 여부
prioritize_time_exit: false
# 아래는 필요 시 추가적으로 활용
# take_profit_pct: null
# stop_loss_pct: null
# trailing_stop_pct: null
# partial_sell_ratio: null   # 0과 1 사이 값, 1이면 전량 매도